language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
install:
  - pip install coveralls
  - pip install .
script:
  - coverage run --branch --source=pyluac --omit=pyluac/parsetab.py setup.py -q test
after_success:
  - coveralls
  - coverage report -m
